stages:
  make_dataset:
    # cmd: python .\src\data\make_dataset.py train.csv
    cmd: python -m src.data.make_dataset train.csv
    deps:
    - .\data\raw\extracted\train.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.test_size
    - make_dataset.random_state
    outs:
    - .\data\interim
